# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d6a74b90b00342988811b3dffe208cdf05de93ae434133f3b917a43da8e8b91ca76514be244e30506535d71073941b9f1b7d5252c6914a183bf7c34ca60fdd

test:
  secret_key_base: 1295502d75ff270b55f209d99f2e07445b1085a5fadb50ead9fbb265b36ce48404b429e9095ee72fe349de0ba446e3da466d2f5ed844816f4df2cc0d0dc6e9d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
